import { Category } from './categories';

export const CategoryColorMap: Map<Category, string> = new Map([
    [Category.BAARI, '#800000'],
    [Category.CAR, '#000000'],
    [Category.CASH, '#808000'],
    [Category.CHARITY, '#469990'],
    [Category.CLOTHING, '#000075'],
    [Category.ELECTRONICSERVICES, '#9A6324'],
    [Category.ENTERTAINMENT, '#e6194B'],
    [Category.FOOD, '#f58231'],
    [Category.HOBBIES, '#ffe119'],
    [Category.HOLIDAYTRIPS, '#bfef45'],
    [Category.HOME, '#3cb44b'],
    [Category.HOMEIMPROVEMENTS, '#42d4f4'],
    [Category.INSURANCES, '#4363d8'],
    [Category.INVESTMENTS, '#911eb4'],
    [Category.MOVINGAROUND, '#f032e6'],
    [Category.OTHER, '#a9a9a9'],
    [Category.PAYCHECK, '#fabed4'],
    [Category.PUBLICTRANSPORTATION, '#ffd8b1'],
    [Category.WELLBEING, '#fffac8'],
    [Category.ELECTRICITY, '#aaffc3'],
    [Category.LOAN, '#dcbeff'],
    [Category.MAINTENANCECHARGE, '#FFFF00'],
]);
