services:
  bankdataserver:
    image: bankdataserver
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
  finance-frontend:
    image: financefrontend
    build: 
      context: .
      dockerfile: ./apps/finance-frontend/Dockerfile
    ports:
      - "4200:80"